### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by drthornt** [drthornt/htu21d-exporter#1]
computers are fun

>  $ ./htu21d-exporter.py
2020-05-17 23:55:45,172 ./htu21d-exporter.py INFO initilize htu sensor
Traceback (most recent call last):
  File "./htu21d-exporter.py", line 118, in <module>
    myhtu = HTU21D()
  File "./htu21d-exporter.py", line 55, in __init__
    self.dev = i2c(HTU21D_ADDR, 1) #HTU21D 0x40, bus 1
  File "./htu21d-exporter.py", line 40, in __init__
    fcntl.ioctl(self.fr, I2C_SLAVE, device)
OSError: [Errno 25] Inappropriate ioctl for device

**Comment by drthornt** [comment]
This is fixed in release [0.1](https://github.com/drthornt/htu21d-exporter/releases/tag/0.1) , so much debug :P.
